name: Publish mod

on: [workflow_dispatch, release, push]


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Wait for build workflow
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        allowed-conclusions: success
        check-name: build
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_artifacts.yml
        commit: ${{ github.sha }}
        name: Artifacts
    - run: ls
