name: Publish mod

on: [release, push]


jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Wait for build workflow
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.ref }}
        allowed-conclusions: success
        check-name: build
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10

    - name: Download artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build_artifacts.yml
        commit: ${{ github.sha }}
        name: Artifacts
        path: artifacts

    - if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew

    - name: Publish to modrinth
      run: gradle publishModrinth
      env: 
        FROM_GITHUB_ACTION: true
        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
